/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solitaire;

/**
 *
 * @author alexi
 */
public class InterfaceModifierPaquet extends javax.swing.JFrame {
    private Utilisateur utilisateur;

    /**
     * Creates new form InterfaceModifierPaquet
     * @param u Utilisateur qui modifie son paquet
     */
    public InterfaceModifierPaquet(Utilisateur u) {
        initComponents();
        this.utilisateur = u;
        this.jTextField_PaquetS.setText(u.getPaquet().getPaquetS());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField_PaquetS = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifier paquet initial");
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new java.awt.GridLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Bebas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modifier le paquet initial");
        jPanel2.add(jLabel1);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel6.setLayout(new java.awt.GridLayout(3, 0));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.GridLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Entrez le nouveau paquet au format chaîne de caractères :");
        jPanel3.add(jLabel2);

        jPanel6.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout());

        jTextField_PaquetS.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_PaquetS.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jTextField_PaquetS.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_PaquetS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_PaquetS.setName("jTextField_PaquetS"); // NOI18N
        jPanel4.add(jTextField_PaquetS);

        jPanel6.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout());

        jButton1.setFont(new java.awt.Font("Bebas", 0, 16)); // NOI18N
        jButton1.setText("MODIFIER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.getAccessibleContext().setAccessibleName("MODIFIER");

        jPanel6.add(jPanel5);

        jSplitPane1.setRightComponent(jPanel6);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Paquet tmp = new Paquet(this.jTextField_PaquetS.getText());
        this.utilisateur.setPaquet(tmp);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField_PaquetS;
    // End of variables declaration//GEN-END:variables
}
