/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solitaire;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import solitaire.fichiers.FabriqueFichier;
import solitaire.fichiers.Fichier;

/**
 *
 * @author alexis
 */
public class InterfaceGraphique extends javax.swing.JFrame {
    private Utilisateur user;
    private int compteur;

    /**
     * Creates new form InterfaceGraphique
     */
    public InterfaceGraphique() {
        initComponents();
        this.user = new Utilisateur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel2 = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton_AfficherPaquet = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton_ModifierPaquet = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jComboBox1 = new javax.swing.JComboBox<>();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_MessageACrypter = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jButton_Crypter = new javax.swing.JButton();
        jButton_ChargerCrypter = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_MasqueJetableCrypter = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_MessageCrypte = new javax.swing.JTextArea();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_MessageADecrypter = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jButton_Decrypter = new javax.swing.JButton();
        jButton_ChargerDecrypter = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_MasqueJetableDecrypter = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea_MessageDecrypte = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cryptage du solitaire");
        setBackground(new java.awt.Color(102, 102, 102));
        setFont(new java.awt.Font("Bebas", 0, 10)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 472));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jSplitPane1.setBackground(new java.awt.Color(102, 102, 102));
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        filler4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.add(filler4);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SOLITAIRE");
        jPanel1.add(jLabel1);

        jPanel4.add(jPanel1);

        filler3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.add(filler3);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler8);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Paquet Initial :");
        jPanel2.add(jLabel2);
        jPanel2.add(filler1);

        jButton_AfficherPaquet.setBackground(new java.awt.Color(204, 204, 204));
        jButton_AfficherPaquet.setFont(new java.awt.Font("Agency FB", 0, 16)); // NOI18N
        jButton_AfficherPaquet.setText("AFFICHER");
        jButton_AfficherPaquet.setMargin(new java.awt.Insets(10, 70, 10, 70));
        jButton_AfficherPaquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AfficherPaquetActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_AfficherPaquet);
        jPanel2.add(filler2);

        jButton_ModifierPaquet.setBackground(new java.awt.Color(204, 204, 204));
        jButton_ModifierPaquet.setFont(new java.awt.Font("Agency FB", 0, 16)); // NOI18N
        jButton_ModifierPaquet.setText("MODIFIER");
        jButton_ModifierPaquet.setMargin(new java.awt.Insets(10, 70, 10, 70));
        jButton_ModifierPaquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifierPaquetActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_ModifierPaquet);
        jPanel2.add(filler6);

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Agency FB", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "METHODE CLASSIQUE", "METHODE OCTETS" }));
        jPanel2.add(jComboBox1);
        jPanel2.add(filler7);

        jPanel4.add(jPanel2);

        jSplitPane1.setTopComponent(jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crypter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));

        jTextArea_MessageACrypter.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea_MessageACrypter.setColumns(20);
        jTextArea_MessageACrypter.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_MessageACrypter.setLineWrap(true);
        jTextArea_MessageACrypter.setRows(5);
        jScrollPane1.setViewportView(jTextArea_MessageACrypter);

        jPanel3.add(jScrollPane1);

        jPanel13.setPreferredSize(new java.awt.Dimension(0, 100));
        jPanel13.setLayout(new java.awt.GridLayout(2, 0));

        jButton_Crypter.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Crypter.setFont(new java.awt.Font("Agency FB", 0, 16)); // NOI18N
        jButton_Crypter.setText("CRYPTER");
        jButton_Crypter.setMargin(new java.awt.Insets(20, 14, 20, 14));
        jButton_Crypter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrypterMouseClicked(evt);
            }
        });
        jPanel13.add(jButton_Crypter);

        jButton_ChargerCrypter.setBackground(new java.awt.Color(204, 204, 204));
        jButton_ChargerCrypter.setFont(new java.awt.Font("Agency FB", 0, 16)); // NOI18N
        jButton_ChargerCrypter.setText("CHARGER FICHIER");
        jButton_ChargerCrypter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChargerCrypterActionPerformed(evt);
            }
        });
        jPanel13.add(jButton_ChargerCrypter);

        jPanel3.add(jPanel13);

        jPanel7.add(jPanel3);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Masque jetable", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea_MasqueJetableCrypter.setEditable(false);
        jTextArea_MasqueJetableCrypter.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea_MasqueJetableCrypter.setColumns(20);
        jTextArea_MasqueJetableCrypter.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_MasqueJetableCrypter.setLineWrap(true);
        jTextArea_MasqueJetableCrypter.setRows(5);
        jScrollPane2.setViewportView(jTextArea_MasqueJetableCrypter);

        jPanel8.add(jScrollPane2);

        jPanel7.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message crypté", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea_MessageCrypte.setEditable(false);
        jTextArea_MessageCrypte.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea_MessageCrypte.setColumns(20);
        jTextArea_MessageCrypte.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_MessageCrypte.setLineWrap(true);
        jTextArea_MessageCrypte.setRows(5);
        jScrollPane3.setViewportView(jTextArea_MessageCrypte);

        jPanel9.add(jScrollPane3);

        jPanel7.add(jPanel9);

        jPanel5.add(jPanel7);
        jPanel5.add(filler5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Décrypter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea_MessageADecrypter.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea_MessageADecrypter.setColumns(20);
        jTextArea_MessageADecrypter.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_MessageADecrypter.setLineWrap(true);
        jTextArea_MessageADecrypter.setRows(5);
        jScrollPane4.setViewportView(jTextArea_MessageADecrypter);

        jPanel10.add(jScrollPane4);

        jPanel14.setPreferredSize(new java.awt.Dimension(0, 100));
        jPanel14.setLayout(new java.awt.GridLayout(2, 0));

        jButton_Decrypter.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Decrypter.setFont(new java.awt.Font("Agency FB", 0, 16)); // NOI18N
        jButton_Decrypter.setText("DECRYPTER");
        jButton_Decrypter.setMargin(new java.awt.Insets(20, 14, 20, 14));
        jButton_Decrypter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DecrypterMouseClicked(evt);
            }
        });
        jPanel14.add(jButton_Decrypter);

        jButton_ChargerDecrypter.setBackground(new java.awt.Color(204, 204, 204));
        jButton_ChargerDecrypter.setFont(new java.awt.Font("Agency FB", 0, 16)); // NOI18N
        jButton_ChargerDecrypter.setText("CHARGER FICHIER");
        jButton_ChargerDecrypter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChargerDecrypterActionPerformed(evt);
            }
        });
        jPanel14.add(jButton_ChargerDecrypter);

        jPanel10.add(jPanel14);

        jPanel6.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Masque jetable", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea_MasqueJetableDecrypter.setEditable(false);
        jTextArea_MasqueJetableDecrypter.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea_MasqueJetableDecrypter.setColumns(20);
        jTextArea_MasqueJetableDecrypter.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_MasqueJetableDecrypter.setLineWrap(true);
        jTextArea_MasqueJetableDecrypter.setRows(5);
        jScrollPane5.setViewportView(jTextArea_MasqueJetableDecrypter);

        jPanel11.add(jScrollPane5);

        jPanel6.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message décrypté", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea_MessageDecrypte.setEditable(false);
        jTextArea_MessageDecrypte.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea_MessageDecrypte.setColumns(20);
        jTextArea_MessageDecrypte.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_MessageDecrypte.setLineWrap(true);
        jTextArea_MessageDecrypte.setRows(5);
        jScrollPane6.setViewportView(jTextArea_MessageDecrypte);

        jPanel12.add(jScrollPane6);

        jPanel6.add(jPanel12);

        jPanel5.add(jPanel6);

        jSplitPane1.setRightComponent(jPanel5);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animationAffichage(JTextArea afficheurMasque, String masque, JTextArea afficheurRes, String res, int duree){
        if(masque.length() != 0){
            int dureePause = (int) (((double) duree/masque.length()) * 1000);
            afficheurMasque.setText("");
            afficheurRes.setText("");
            JFrame fenetre = this;
            compteur = 0;
            Timer timer = new Timer(dureePause, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if(compteur < res.length()) {
                        afficheurMasque.setText(afficheurMasque.getText() + masque.charAt(compteur));
                        afficheurRes.setText(afficheurRes.getText() + res.charAt(compteur));
                        compteur++;
                        fenetre.repaint();
                    } else {
                        ((Timer)e.getSource()).stop();
                    }
                }
            });
            timer.setRepeats(true);
            timer.start();
        }
    }
    
    private void jButton_CrypterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrypterMouseClicked
        String messageACrypter = this.jTextArea_MessageACrypter.getText();
        Message messageCrypte;
        if(this.jComboBox1.getSelectedIndex()==0)
            messageCrypte = this.user.crypter(messageACrypter);
        else
            messageCrypte = this.user.crypterAvecBytes(messageACrypter);
        //this.jTextArea_MasqueJetableCrypter.setText(messageCrypte.getMasqueJetable());
        this.animationAffichage(this.jTextArea_MasqueJetableCrypter, messageCrypte.getMasqueJetable(), this.jTextArea_MessageCrypte, messageCrypte.getMessageArrivee(), 5);
    }//GEN-LAST:event_jButton_CrypterMouseClicked

    private void jButton_DecrypterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DecrypterMouseClicked
        String messageADecrypter = this.jTextArea_MessageADecrypter.getText();
        Message messageDecrypte;
        if(this.jComboBox1.getSelectedIndex()==0)
            messageDecrypte = this.user.decrypter(messageADecrypter);
        else
            messageDecrypte = this.user.decrypterAvecBytes(messageADecrypter);
        this.animationAffichage(this.jTextArea_MasqueJetableDecrypter, messageDecrypte.getMasqueJetable(), this.jTextArea_MessageDecrypte, messageDecrypte.getMessageArrivee(), 5);
    }//GEN-LAST:event_jButton_DecrypterMouseClicked

    private void jButton_ModifierPaquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifierPaquetActionPerformed
        InterfaceModifierPaquet mp = new InterfaceModifierPaquet(this.user);
        mp.setVisible(true);
    }//GEN-LAST:event_jButton_ModifierPaquetActionPerformed

    private void jButton_AfficherPaquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AfficherPaquetActionPerformed
        InterfaceAfficherPaquet ap = new InterfaceAfficherPaquet(this.user.getPaquet());
        ap.setVisible(true);
    }//GEN-LAST:event_jButton_AfficherPaquetActionPerformed

    private String getPathFile(ArrayList<FileNameExtensionFilter> filter){
        String path = "";
        JFileChooser chooser = new JFileChooser();
        for(FileNameExtensionFilter filtre : filter) chooser.setFileFilter(filtre);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) path = chooser.getSelectedFile().getName();
        
        return path;
    }
    
    private void jButton_ChargerCrypterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChargerCrypterActionPerformed
        ArrayList<FileNameExtensionFilter> filters = new ArrayList<>();
        filters.add(new FileNameExtensionFilter("Fichiers texte", "txt"));
        filters.add(new FileNameExtensionFilter("Fichiers image", "jpg", "png", "gif"));
        String path = this.getPathFile(filters);
        Fichier f = FabriqueFichier.creerFichier(path);
        Fichier fb = FabriqueFichier.creerFichier(".bin");
        if(f != null){
            byte[] contenu = f.charger(path);
            jTextArea_MasqueJetableCrypter.setText("Cryptage en cours ...\n");
            byte[] resultat = this.user.crypter(contenu);
            this.jTextArea_MasqueJetableCrypter.setText(this.jTextArea_MasqueJetableCrypter.getText() + "Cryptage terminé.\n");
            this.jTextArea_MasqueJetableCrypter.setText(this.jTextArea_MasqueJetableCrypter.getText() + "Enregistrement du fichier crypté.");
            fb.sauver(path + ".bin", resultat);
            this.jTextArea_MessageCrypte.setText("Terminé : " + path + ".bin");
        }
        else this.jTextArea_MessageCrypte.setText("Erreur : format inconnu - " + path);
    }//GEN-LAST:event_jButton_ChargerCrypterActionPerformed

    private void jButton_ChargerDecrypterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChargerDecrypterActionPerformed
        ArrayList<FileNameExtensionFilter> filters = new ArrayList<>();
        filters.add(new FileNameExtensionFilter("Fichiers binaires cryptés", "bin"));
        String path = this.getPathFile(filters);
        System.out.println(path);
        Fichier f = FabriqueFichier.creerFichier(path);
        Fichier fb = FabriqueFichier.creerFichier(".bin");
        if(f != null){
            byte[] contenu = fb.charger(path);
            this.jTextArea_MasqueJetableDecrypter.setText("Décryptage en cours ...\n");
            byte[] resultat = this.user.decrypter(contenu);
            this.jTextArea_MasqueJetableDecrypter.setText(this.jTextArea_MasqueJetableDecrypter.getText() + "Décryptage terminé.\n");
            this.jTextArea_MasqueJetableDecrypter.setText(this.jTextArea_MasqueJetableDecrypter.getText() + "Enregistrement du fichier décrypté.");
            String nouveauNom = path.replace(".bin", "");
            nouveauNom = nouveauNom.replace(".", "_decrypted.");
            f.sauver(nouveauNom, resultat);
            this.jTextArea_MessageDecrypte.setText("Terminé : " + nouveauNom);
        }
        else this.jTextArea_MessageDecrypte.setText("Erreur : format inconnu - " + path);
    }//GEN-LAST:event_jButton_ChargerDecrypterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JButton jButton_AfficherPaquet;
    private javax.swing.JButton jButton_ChargerCrypter;
    private javax.swing.JButton jButton_ChargerDecrypter;
    private javax.swing.JButton jButton_Crypter;
    private javax.swing.JButton jButton_Decrypter;
    private javax.swing.JButton jButton_ModifierPaquet;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea_MasqueJetableCrypter;
    private javax.swing.JTextArea jTextArea_MasqueJetableDecrypter;
    private javax.swing.JTextArea jTextArea_MessageACrypter;
    private javax.swing.JTextArea jTextArea_MessageADecrypter;
    private javax.swing.JTextArea jTextArea_MessageCrypte;
    private javax.swing.JTextArea jTextArea_MessageDecrypte;
    // End of variables declaration//GEN-END:variables
}
